spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pradeepbr2003/config-service
          search-paths:
            - '{profile}'
          refresh-rate: 0
        default-label: main
server:
  port: 8181
